version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "movie-tracker-aws"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-ttmaw6d1qxfb"
s3_prefix = "movie-tracker-aws"
region = "eu-west-2"
capabilities = "CAPABILITY_IAM"
