AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app

  Sample SAM Template for sam-app

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  NamesTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: movieTracker__dev__trailers
      PrimaryKey:
        Name: id
        Type: String
      SSESpecification:
        SSEEnabled: true
  TestFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: lambdaFunctions/testFunction/
      Handler: testFunction.lambdaHandler
      Runtime: nodejs12.x
      Events:
        Test:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /test
            Method: get
  AddTrailersToDb:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: lambdaFunctions/addTrailersToDb/
      Handler: addTrailersToDb.lambdaHandler
      Runtime: nodejs12.x
      Policies:
        - DynamoDBCrudPolicy:
          TableName: !Ref movieTracker__dev__trailers
      Events:
        Test:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /addTrailersToDb
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  TestFunctionApi:
    Description: "API Gateway endpoint URL for Prod stage for test function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/test/"
  TestFunction:
    Description: "Test Lambda Function ARN"
    Value: !GetAtt TestFunction.Arn
  TestFunctionIamRole:
    Description: "Implicit IAM Role created for Test function"
    Value: !GetAtt TestFunctionRole.Arn
  AddTrailersToDbApi:
    Description: "API Gateway endpoint URL for Prod stage for addTrailersToDb function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/addTrailersToDb/"
  AddTrailersToDb:
    Description: "AddTrailersToDb Lambda Function ARN"
    Value: !GetAtt AddTrailersToDb.Arn
  AddTrailersToDbIamRole:
    Description: "Implicit IAM Role created for AddTrailersToDb function"
    Value: !GetAtt AddTrailersToDb.Arn
